version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    command: npm start
